<form action="/users/<?= htmlspecialchars($id) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
      <label>
          Nickname
          <input type="text" name="user[name]" value="<?= htmlspecialchars($user[$id]['name'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['name'])): ?>
          <div><?= $errors['name'] ?></div>
      <?php endif ?>
    </div>
        <div>
      <label>
          Email
          <input type="email" name="user[email]" value="<?= htmlspecialchars($user[$id]['email'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['email'])): ?>
          <div><?= $errors['email'] ?></div>
      <?php endif ?>
    </div>

    <input type="submit" value="Update">
</form>

