<form action="" method="get">
<input type="submit" name="email" value="Logout" href="/users"/>
</form>

<form action="" method="get">
<input type="search" name="usersSearch" value="<?= htmlspecialchars($usersSearch ?? '')?>" />
<input type="submit" value="Search" />
</form>
<ul>
<?php
foreach ($users as $key => $value) : ?>
<li>Id: <?= $key ?> || nickname: <?= $value['name'] ?> || email: <?= $value['email'] ?>
<span><a href="/users/<?= $key ?>/edit">Edit</a></span></li>
<?php endforeach ?>
</ul>

